{% set name = "ParmEd" %}
{% set version = "2.7.3" %}
{% set sha256 = "56b3097625be3a5037a5b3d7c4d9467a97f0dd44fea79cf2873f0e56d3409975" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - parmed = parmed.scripts:clapp
    - xparmed = parmed.scripts:guiapp

requirements:
  build:
    - python
    - toolchain
    - setuptools

  run:
    - python
    - numpy
    - pandas

test:
  imports:
   - parmed
   - parmed.amber
   - parmed.modeller
   - parmed.tinker
   - parmed.unit
   - parmed.amber.mdin
   - parmed.charmm
   - parmed.formats.pdbx
   - parmed.rosetta
   - parmed.rdkit
   - parmed.formats
   - parmed.utils.fortranformat
   - parmed.openmm
   - parmed.utils
   - parmed.gromacs
   - parmed.tools
   - parmed.namd
   - parmed.tools.gui
   - parmed.tools.simulations
  

about:
  home: http://parmed.github.io/ParmEd
  license: LGPL-2.1
  license_file: GNU_LGPL_v2
  summary: >
     "A package for parsing, interconverting, manipulating, and simulating biomolecular simulations
      with many packages. Note: This package should be identical to the one in the "omnia" conda channel
  dev_url: https://github.com/ParmEd/ParmEd
  doc_url: http://parmed.github.io/ParmEd


extra:
  recipe-maintainers:
    - avirshup
